Fix compile error due to variable declaration inside a 'switch' case
A recently added 'switch' statement for handling different
dispatcher types includes a line of code where a variable is
declared immediately after a case label without being
enclosed in braces.

This causes compilation failures with certain compilers, which
appear as:

    libxdp.c: In function 'check_dispatcher_version':
    libxdp.c:2189:3: error: a label can only be part of a statement and a declaration is not a statement
     2189 |   struct xdp_dispatcher_config_v1 *config = (void *)buf;
          |   ^~~~~~

Adding braces around the code for the case will avoid this problem.

Observed when following the standard build instructions on
Ubuntu 20.04 (gcc 9.4.0, clang 15.0.7).

Signed-off-by: Shane Alcock <shane@alcock.co.nz>