libxdp: Use prog->prog_name directly in debug output
At higher optimisation levels, the compiler seems to think that the NULL
check in xdp_program__name() implies that the prog pointer can be NULL.
Which makes it complain about the unconditional use in debug output with
somewhat cryptic errors like:

In file included from libxdp.c:37:
libxdp.c: In function ‘xdp_multiprog__pin’:
libxdp_internal.h:38:37: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
   38 |                 libxdp_print(level, "libxdp: " fmt, ##__VA_ARGS__); \
      |                                     ^~~~~~~~~~
libxdp_internal.h:43:28: note: in expansion of macro ‘__pr’
   43 | #define pr_debug(fmt, ...) __pr(LIBXDP_DEBUG, fmt, ##__VA_ARGS__)
      |                            ^~~~
libxdp.c:3097:17: note: in expansion of macro ‘pr_debug’
 3097 |                 pr_debug("Pinned prog %s at %s\n", xdp_program__name(prog), buf);
      |                 ^~~~~~~~

This is, in fact, a false positive, but in the absence of a way to tell the
compiler that, let's just change the code in question to use the
prog->prog_name field directly.

Signed-off-by: Toke Høiland-Jørgensen <toke@redhat.com>