xdp-dump: add support for >16 XDP eBPF entry function names
The Linux API does not provide the full name of the attached eBPF
entry function if it's longer than 15 characters. xdpdump will try to
guess the correct function name from the available BTF debug
information. However, if multiple functions exist with the same
leading name, it can not pick the correct one. It will dump the
available functions, and you can choose the correct one, and supply it
with the -m option. For example:

$ xdpdump -i eth0
ERROR: Can't identify the full XDP main function!
The following is a list of candidates:
  xdp_test_prog_with_a_long_name
  xdp_test_prog_with_a_long_name_too
  xdp_test_prog_w
Please use the -m option to pick the correct one.

$ ./xdpdump -i eth0 -m xdp_test_prog_with_a_long_name
1588252724.025055871: @entry: packet size 102 bytes on if_index 2, rx queue 0
1588252724.026463296: @entry: packet size 66 bytes on if_index 2, rx queue 0
1588252724.026786186: @entry: packet size 66 bytes on if_index 2, rx queue 0

Signed-off-by: Eelco Chaudron <echaudro@redhat.com>