libxdp: fix build on musl
In musl, PATH_MAX is defined in limits.h. Include it in libxdp.c to fix
building systems using musl libc.

libxdp.c: In function 'find_bpffs':
libxdp.c:406:33: error: 'PATH_MAX' undeclared (first use in this function)
  406 |         static char bpf_wrk_dir[PATH_MAX];
      |                                 ^~~~~~~~

Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>